name: Publish docker image

on:
  push:
    tags: "*"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: github-repo
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.repository }}

    - name: Publish to GitHub packages
      uses: whoan/docker-build-with-cache-action@v2
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        image_name: ${{ steps.github-repo.outputs.lowercase }}/plex-bot
